from __future__ import annotations

import os

import httpx

from .models import Posting
from .store import Store

_TIER_LABELS = {"Tier 1", "Tier 2"}


def fire_github_alerts(postings: list[Posting], store: Store) -> int:
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")
    if not token or not repo:
        return 0

    to_alert = store.get_unalerted_tier_postings()
    if not to_alert:
        return 0

    posted_ids = {p.id for p in postings}
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    count = 0
    for posting in to_alert:
        if posting.id not in posted_ids:
            store.mark_alerted(posting.id)
            continue

        posted = posting.posted_date.strftime("%Y-%m-%d") if posting.posted_date else "—"
        title = f"[New] {posting.company} — {posting.role_title} ({posting.tier})"
        body = (
            f"**{posting.company}** ({posting.tier}) just posted a new role.\n\n"
            f"| Field | Value |\n"
            f"|-------|-------|\n"
            f"| Role | {posting.role_title} |\n"
            f"| Track | {posting.track or '—'} |\n"
            f"| MBA | {posting.mba_preference or '—'} |\n"
            f"| Location | {posting.location or '—'} |\n"
            f"| Cycle | {posting.cycle} |\n"
            f"| Posted | {posted} |\n\n"
            f"[Apply →]({posting.apply_url})\n\n"
            f"---\n_Auto-generated by mba-internship-engine_"
        )
        try:
            resp = httpx.post(
                f"https://api.github.com/repos/{repo}/issues",
                headers=headers,
                json={"title": title, "body": body},
                timeout=30,
            )
            resp.raise_for_status()
            store.mark_alerted(posting.id)
            count += 1
        except Exception as exc:
            print(f"  [alert] Failed to create issue for {posting.company}: {exc}")

    return count
