from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from ..models import Posting, RunStats
from ..radar import RadarRow

_MARKER = "<!-- AUTOGENERATED -->"
_PRODUCT_TRACKS = {"product", "product_strategy", "ai_product"}


def _radar_table(rows: list[RadarRow]) -> str:
    lines = [
        "| Company | Tier | Expected | Status |",
        "|---------|------|----------|--------|",
    ]
    for row in rows:
        if row.status == "verified":
            s = f"🎯 Live since {row.verified_date} ({row.live_count} roles)"
        elif row.status == "live":
            s = f"✅ Live ({row.live_count} roles)"
        else:
            s = "⏳ Waiting"
        lines.append(f"| {row.company} | {row.tier} | {row.typical_open or '—'} | {s} |")
    return "\n".join(lines)


def _posting_table(postings: list[Posting]) -> str:
    if not postings:
        return "_No postings found._"
    lines = [
        "| Company | Role | Track | MBA | Location | Posted | Apply |",
        "|---------|------|-------|-----|----------|--------|-------|",
    ]
    for p in postings:
        posted = p.posted_date.strftime("%Y-%m-%d") if p.posted_date else "—"
        loc = (p.location or "—")[:35].replace("|", "/")
        role = (p.role_title or "").replace("|", "/")[:55]
        lines.append(
            f"| {p.company} | {role} | {p.track or '—'} | {p.mba_preference or '—'} "
            f"| {loc} | {posted} | [Apply]({p.apply_url}) |"
        )
    return "\n".join(lines)


def render_readme(
    postings: list[Posting],
    unstated_postings: list[Posting],
    radar_rows: list[RadarRow],
    stats: RunStats,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    main = [p for p in postings if p.track in _PRODUCT_TRACKS]
    pmm = [p for p in postings if p.track == "product_marketing"]
    other = [p for p in postings if p.track == "other_mba_tech"]

    parts: list[str] = [
        "<!-- AUTOGENERATED — do not edit below this line -->",
        "",
        f"**Last updated:** {now}  ",
        f"**Boards:** {stats.boards_succeeded}/{stats.boards_attempted} succeeded  ",
        f"**Summer 2027 (stated, US):** {len(postings)} roles  ",
        f"**Cycle unstated (US):** {len(unstated_postings)} roles",
        "",
        "> **Coverage disclaimer:** This engine scrapes public employer ATS feeds only. "
        "It cannot access 12twenty, Handshake, HBS CMS, LinkedIn, Indeed, or any "
        "login-required platform. Use it alongside — not instead of — those resources.",
        "",
        "## 🎯 Drop Radar — Tier 1 & Tier 2",
        "",
        "_Typical opening dates are estimates from public recruiting timelines, labeled as "
        "estimates until a real posting appears (🎯 = verified from live feed)._",
        "",
        _radar_table(radar_rows),
        "",
        "---",
        "",
        "## Summer 2027 — Explicitly Stated",
        "",
        f"### Product / Strategy / AI Product ({len(main)} roles)",
        "",
        _posting_table(main),
    ]

    if pmm:
        parts += [
            "",
            f"<details><summary>Product Marketing ({len(pmm)} roles)</summary>",
            "",
            _posting_table(pmm),
            "",
            "</details>",
        ]

    if other:
        parts += [
            "",
            f"<details><summary>Other MBA Tech ({len(other)} roles)</summary>",
            "",
            _posting_table(other),
            "",
            "</details>",
        ]

    if unstated_postings:
        shown = unstated_postings[:50]
        parts += [
            "",
            f"## Cycle Not Stated ({len(unstated_postings)} roles)",
            "",
            "_MBA-level PM roles at tracked companies with no explicit Summer 2027 mention. "
            "Worth watching — many companies omit the cycle year early in the season._",
            "",
            _posting_table(shown),
        ]
        if len(unstated_postings) > 50:
            parts.append(f"\n_…and {len(unstated_postings) - 50} more — see [data/postings.csv](data/postings.csv)_")

    parts += [
        "",
        "---",
        "",
        f"_Run stats: {stats.boards_succeeded}/{stats.boards_attempted} boards · "
        f"{stats.roles_found} total roles fetched · generated {now}_",
    ]

    return "\n".join(parts)


def write_readme(
    path: Path,
    postings: list[Posting],
    unstated_postings: list[Posting],
    radar_rows: list[RadarRow],
    stats: RunStats,
) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if _MARKER in existing:
        static_part = existing[: existing.index(_MARKER)]
    else:
        static_part = existing.rstrip() + "\n\n" if existing else ""
    path.write_text(static_part + render_readme(postings, unstated_postings, radar_rows, stats), encoding="utf-8")
